version: '3'
services: 
  app:
    build: .
    env_file: 
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    ports: 
      - '3000:3000'
    volumes:
      - .:/g_app
      - public-data:/g_app/public
      - tmp-data:/g_app/tmp
      - sockets:/g_app/tmp/sockets
    depends_on: 
      - db
      - chrome
    tty: true
    stdin_open: true
  web:
    build: 
      context: containers/nginx
    ports: 
      - '80:80'
    volumes: 
      - public-data:/g_app/public
      - tmp-data:/g_app/tmp
      - sockets:/g_app/tmp/sockets
    depends_on: 
      - app
  db:
    image: mysql:5.7
    env_file: 
      - ./environments/db.env
    ports: 
      - '3306:3306'
    volumes: 
      - db-data:/var/lib/mysql
  chrome:
    image: selenium/standalone-chrome:3.141.59-dubnium
    ports:
      - 4444:4444
volumes: 
  public-data:
  tmp-data:
  db-data:
  sockets:
